# -*- coding: utf-8 -*-
"""Define words.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u4V5OYFyCX3czl6HuOQVBSc7F-D3ZpJI
"""

pip install pymorphy2

pip install pyTelegramBotAPI

import telebot
import pymorphy2
import re

# Токен вашего бота от BotFather
TOKEN = '7868924098:AAG8bPf8RXn6DqVMkSn323RngxFYzZva5ls'

# Инициализация бота и морфологического анализатора
bot = telebot.TeleBot(TOKEN)
morph = pymorphy2.MorphAnalyzer()

# Словарь с расшифровками сокращений
descriptions = {
    "СУЩ": "имя существительное", "ПРИЛ": "имя прилагательное (полное)", "КР_ПРИЛ": "имя прилагательное (краткое)",
    "КОМП": "компаратив", "ГЛ": "глагол (личная форма)", "ИНФ": "глагол (инфинитив)", "ПРИЧ": "причастие (полное)",
    "КР_ПРИЧ": "причастие (краткое)", "ДЕЕПР": "деепричастие", "ЧИСЛ": "числительное", "Н": "наречие",
    "МС": "местоимение-существительное", "ПРЕДК": "предикатив", "ПР": "предлог", "СОЮЗ": "союз", "ЧАСТ": "частица",
    "МЕЖД": "междометие", "од": "одушевлённое", "неод": "неодушевлённое", "мр": "мужской род", "жр": "женский род",
    "ср": "средний род", "мж": "общий род", "ед": "единственное число", "мн": "множественное число",
    "им": "именительный падеж", "рд": "родительный падеж", "дт": "дательный падеж", "вн": "винительный падеж",
    "тв": "творительный падеж", "пр": "предложный падеж", "сов": "совершенный вид", "несов": "несовершенный вид",
    "перех": "переходный", "неперех": "непереходный", "1л": "1 лицо", "2л": "2 лицо", "3л": "3 лицо",
    "наст": "настоящее время", "прош": "прошедшее время", "буд": "будущее время", "изъяв": "изъявительное наклонение",
    "повел": "повелительное наклонение", "действ": "действительный залог", "страд": "страдательный залог",
    "разг": "разговорное", "жарг": "жаргонное", "аббр": "аббревиатура",
}

# Функция для замены сокращений на полные расшифровки
def decode_morph_analysis(tags):
    return [descriptions.get(tag, tag) for tag in tags]

# Команда /start
@bot.message_handler(commands=['start'])
def send_welcome(message):
    bot.reply_to(message, "Привет! Введите предложение, чтобы узнать морфологический разбор каждого слова.")

# Основная функция для обработки сообщений
@bot.message_handler(func=lambda message: True)
def analyze_sentence(message):
    sentence = message.text
    words = sentence.split()  # Разделение предложения на слова
    responses = []

    # Обработка каждого слова в предложении
    for word in words:
        parses = morph.parse(word)
        word_responses = [f"Слово: {word}"]

        # Обработка каждого разбора слова
        for index, p in enumerate(parses, start=1):
            z = re.split(r'[,\s]+', p.tag.cyr_repr)
            decoded_z = decode_morph_analysis(z)
            response = f"Вариант {index}: {', '.join(decoded_z)}"
            word_responses.append(response)

        # Объединение всех разборов для одного слова
        responses.append("\n".join(word_responses))

    # Отправка всех разборов для всех слов
    bot.send_message(message.chat.id, "\n\n".join(responses))

# Запуск бота
bot.polling()

